COMMANDS = {
    "/help": "Show available commands",
    "/clear": "Clear current session",
    "/analyze": "Analyze a startup",
    "/market": "Show market analysis",
    "/competition": "Show competition analysis",
    "/founder": "Show founder analysis",
    "/finance": "Show finance analysis",
    "/risk": "Show risk analysis",
    "/investment": "Show investment recommendation",
    "/memo": "Show final investment memo",
    "/agents":      "List registered agents",
    "/memo-export": "Export last memo as Markdown or JSON (e.g. /memo-export json)",
    "/exit":        "Exit Venture Sage",
}
